/**
 * generated by Xtext
 */
package org.eclipse.etrice.core.common.base;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.etrice.core.common.base.BasePackage#getNumberLiteral()
 * @model
 * @generated
 */
public interface NumberLiteral extends Literal
{
} // NumberLiteral
