/**
 * @author generated by eTrice
 *
 * Source File of DataClass DTcpControl
 * 
 */

#include "DTcpControl.h"

#include <string.h>



/*--------------------- operations ---------------------*/

void DTcpControl_deepCopy(DTcpControl* source, DTcpControl* target) {
	memcpy(target, source, sizeof(DTcpControl));
}


