/**
 * @author generated by eTrice
 *
 * this class contains the main function running component SubSystemHFSMTest
 * it instantiates SubSystemHFSMTest and starts and ends the lifecycle
 */

package org.eclipse.etrice.integration.tests;

import org.eclipse.etrice.runtime.java.modelbase.SubSystemRunnerBase;

class SubSystemHFSMTestRunner extends SubSystemRunnerBase {

	/**
     * main function
     * creates the main component and starts and stops the lifecycle
     */
	public static void main(String[] args) {
		// instantiate the main component
		SubSystemHFSMTest main_component = new SubSystemHFSMTest("SubSystemHFSMTest");
		
		run(main_component, args);
	}
};
