# for make.xml

#include ${MODELLIB_ROOTDIR}/buildTools/modellib.mk
include ${RUNTIME_ROOTDIR}/buildTools/runtime.mk

# --- 
IN_TARGET := ${APP_TARGET}
IN_BUILD_DIR := ${APP_BUILD_DIR}
IN_INCDIRS += ${APP_SRCDIRS_REC}
IN_SRCDIRS_REC += ${APP_SRCDIRS_REC}
#---

# Create rules
include ${RUNTIME_ROOTDIR}/buildTools/Makefile.mk