/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

import com.google.inject.Inject;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class RoomScopeProvider extends org.eclipse.etrice.core.fsm.scoping.FSMScopeProvider {

	@Inject
	private RoomScopeProviderDelegate delegate;
	
	@Override
	public IScope getScope(EObject context, EReference reference) {
		IScope scope = delegate.getScope(context, reference);
		return scope!=null ? scope : super.getScope(context, reference);
	} 
}
