/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTimer
 * 
 */

#ifndef _ETRICE_API_TIMER_PTIMER_UTILS_H_
#define _ETRICE_API_TIMER_PTIMER_UTILS_H_

#include "etrice/api/timer/PTimer.h"

/*
 * access macros for operations and attributes
*/

/* conjugate port class */

/* operations */

/* attributes */
#define status (((PTimerConjPort_var*)(self->varData))->status)

#endif /* _ETRICE_API_TIMER_PTIMER_UTILS_H_ */

