/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PLogger
 * 
 */

#ifndef _ETRICE_API_LOGGER_PLOGGER_UTILS_H_
#define _ETRICE_API_LOGGER_PLOGGER_UTILS_H_

#include "etrice/api/logger/PLogger.h"

/*
 * access macros for operations and attributes
*/

/* conjugate port class */

/* operations */
#define log(message) PLoggerConjPort_log(self, message)
#define logF(format, ...) PLoggerConjPort_logF(self, format, __VA_ARGS__)

/* attributes */

#endif /* _ETRICE_API_LOGGER_PLOGGER_UTILS_H_ */

