/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.common.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.etrice.core.common.ui.internal.BaseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BaseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BaseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BaseActivator.getInstance().getInjector(BaseActivator.ORG_ECLIPSE_ETRICE_CORE_COMMON_BASE);
	}
	
}
