/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.scoping;

import org.eclipse.etrice.core.fsm.scoping.FSMScopeProvider;

public abstract class AbstractRoomScopeProvider extends FSMScopeProvider {
}
