/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTcpPayload
 * 
 */

#ifndef _ETRICE_API_TCP_PTCPPAYLOAD_UTILS_H_
#define _ETRICE_API_TCP_PTCPPAYLOAD_UTILS_H_

#include "etrice/api/tcp/PTcpPayload.h"

/*
 * access macros for operations and attributes
*/


#endif /* _ETRICE_API_TCP_PTCPPAYLOAD_UTILS_H_ */

