/**
 * generated by Xtext
 */
package org.eclipse.etrice.core.fsm.fSM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Continuation Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * <br>Continuation transitions start at entry or exit points
 * ({@link EntryPoint}s or {@link ExitPoint}s) or form
 * the default branch of a {@link ChoicePoint}.
 * 
 * <!-- end-model-doc -->
 *
 *
 * @see org.eclipse.etrice.core.fsm.fSM.FSMPackage#getContinuationTransition()
 * @model
 * @generated
 */
public interface ContinuationTransition extends NonInitialTransition
{
} // ContinuationTransition
