/**
 * generated by Xtext
 */
package org.eclipse.etrice.core.fsm.fSM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * <br>There can be at most one initial transition in a {@link StateGraph}.
 * It defines the starting point of the state graph and is traversed
 * exactly once when the state graph is accessed for the first time.
 * 
 * <!-- end-model-doc -->
 *
 *
 * @see org.eclipse.etrice.core.fsm.fSM.FSMPackage#getInitialTransition()
 * @model
 * @generated
 */
public interface InitialTransition extends Transition
{
} // InitialTransition
