/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.scoping;

import org.eclipse.etrice.core.common.scoping.BaseScopeProvider;

public abstract class AbstractConfigScopeProvider extends BaseScopeProvider {
}
