/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.etphys.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.etrice.core.etphys.ETPhysRuntimeModule;
import org.eclipse.etrice.core.etphys.ETPhysStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ETPhysIdeSetup extends ETPhysStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ETPhysRuntimeModule(), new ETPhysIdeModule()));
	}
	
}
