# for make.xml
include ${RUNTIME_ROOTDIR}/buildTools/runtime.mk

# --- 
IN_TARGET 		:= $(notdir $(shell pwd)).exe
IN_BUILD_DIR 	:= ./bin
IN_INCDIRS 		+= ./src
IN_SRCDIRS_REC 	+= ./src
#---


# Create rules
include ${RUNTIME_ROOTDIR}/buildTools/Makefile.mk