/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.common.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.etrice.core.common.parser.antlr.internal.InternalBaseParser;
import org.eclipse.etrice.core.common.services.BaseGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BaseParser extends AbstractAntlrParser {

	@Inject
	private BaseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBaseParser createParser(XtextTokenStream stream) {
		return new InternalBaseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Annotation";
	}

	public BaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
