/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PTrafficLight
 * 
 */

#include "PTrafficLight.h"
#include "debugging/etMSCLogger.h"


/*--------------------- port methods */

void PTrafficLightPort_greenForCarDone(const PTrafficLightPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightPort", "greenForCarDone")
		etPort_sendMessage(self, PTrafficLight_OUT_greenForCarDone, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightReplPort_greenForCarDone_broadcast(const PTrafficLightReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightReplPort", "greenForCarDone")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[i]), PTrafficLight_OUT_greenForCarDone, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightReplPort_greenForCarDone(const PTrafficLightReplPort* self, int idx) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightReplPort", "greenForCarDone")
	if (0<=idx && idx<((etReplPort*)self)->size) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[idx]), PTrafficLight_OUT_greenForCarDone, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PTrafficLightPort_greenForPedDone(const PTrafficLightPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightPort", "greenForPedDone")
		etPort_sendMessage(self, PTrafficLight_OUT_greenForPedDone, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightReplPort_greenForPedDone_broadcast(const PTrafficLightReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightReplPort", "greenForPedDone")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[i]), PTrafficLight_OUT_greenForPedDone, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightReplPort_greenForPedDone(const PTrafficLightReplPort* self, int idx) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightReplPort", "greenForPedDone")
	if (0<=idx && idx<((etReplPort*)self)->size) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[idx]), PTrafficLight_OUT_greenForPedDone, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PTrafficLightReplPort_getReplication(const PTrafficLightReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PTrafficLightConjPort_greenForCar(const PTrafficLightConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjPort", "greenForCar")
		etPort_sendMessage(self, PTrafficLight_IN_greenForCar, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightConjReplPort_greenForCar_broadcast(const PTrafficLightConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjReplPort", "greenForCar")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[i]), PTrafficLight_IN_greenForCar, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightConjReplPort_greenForCar(const PTrafficLightConjReplPort* self, int idx) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjReplPort", "greenForCar")
	if (0<=idx && idx<((etReplPort*)self)->size) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[idx]), PTrafficLight_IN_greenForCar, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PTrafficLightConjPort_greenForPed(const PTrafficLightConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjPort", "greenForPed")
		etPort_sendMessage(self, PTrafficLight_IN_greenForPed, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightConjReplPort_greenForPed_broadcast(const PTrafficLightConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjReplPort", "greenForPed")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[i]), PTrafficLight_IN_greenForPed, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTrafficLightConjReplPort_greenForPed(const PTrafficLightConjReplPort* self, int idx) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTrafficLightConjReplPort", "greenForPed")
	if (0<=idx && idx<((etReplPort*)self)->size) {
		etPort_sendMessage(((etPort*)&((etReplPort*)self)->ports[idx]), PTrafficLight_IN_greenForPed, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PTrafficLightConjReplPort_getReplication(const PTrafficLightConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */

/* message names as strings for debugging (generate MSC) */
static const char* const PTrafficLight_messageStrings[] = {"MIN", "greenForCarDone","greenForPedDone","greenForCar", "greenForPed", "MAX"};

const char* PTrafficLight_getMessageString(int msg_id) {
	if (msg_id<PTrafficLight_MSG_MIN || msg_id>PTrafficLight_MSG_MAX+1){
		/* id out of range */
		return "Message ID out of range";
	}
	else{
		return PTrafficLight_messageStrings[msg_id];
	}
}
