/**
 * @author generated by eTrice
 *
 * Source File of SubSystemClass SSTraffic
 * 
 */

#include "SSTraffic.h"

/* include instances for all classes */
#include "SSTraffic_Inst.h"
#include "SSTraffic_Disp.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"

#include "platform/etTimer.h"
#include "etRuntimeConfig.h"


/* data for SubSysten SSTraffic */
typedef struct SSTraffic {
	char *name;
	volatile int shutdownRequest;
} SSTraffic;

static SSTraffic SSTrafficInst = {"SSTraffic",0};

void SSTraffic_initActorInstances(void);
void SSTraffic_constructActorInstances(void);

void SSTraffic_init(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "init")
	etLogger_logInfoF("%s_init", SSTrafficInst.name);
	
	/* construct all actors */
	SSTraffic_constructActorInstances();
	
	/* initialization of all message services */
	etMessageService_init(&msgService_Thread1, msgBuffer_Thread1, MESSAGE_POOL_MAX, MESSAGE_BLOCK_SIZE, MsgDispatcher_Thread1_receiveMessage);
	
	/* init all actors */
	SSTraffic_initActorInstances();
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void SSTraffic_start(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "start")
	etLogger_logInfoF("%s_start", SSTrafficInst.name);
	ET_MSC_LOGGER_SYNC_EXIT
}

void SSTraffic_run(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "run")
	
	#ifdef ET_RUNTIME_ENDLESS
		while(!(SSTrafficInst.shutdownRequest)){
			if (etTimer_executeNeeded()){
				etMessageService_execute(&msgService_Thread1);
				ATimingService_execute(&_LSTraffic_main_TimingService);
			}
		}
	#else
		uint32 loopCounter = 0;
		while(!(SSTrafficInst.shutdownRequest)){
			if (etTimer_executeNeeded()){
				etMessageService_execute(&msgService_Thread1);
				ATimingService_execute(&_LSTraffic_main_TimingService);
				if (loopCounter++ > ET_RUNTIME_MAXLOOP){
					break;
				}
			}
		}
	#endif
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void SSTraffic_stop(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "stop")
	etLogger_logInfoF("%s_stop", SSTrafficInst.name);
	ET_MSC_LOGGER_SYNC_EXIT
}

void SSTraffic_destroy(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "destroy")
	etLogger_logInfoF("%s_destroy", SSTrafficInst.name);
	TrafficController_dtor(&_LSTraffic_main_application_controller);
	ATcpClient_dtor(&_LSTraffic_main_application_light2_trafficLightSocket);
	ATcpClient_dtor(&_LSTraffic_main_application_light1_trafficLightSocket);
	ET_MSC_LOGGER_SYNC_EXIT
}

void SubSysClass_shutdown(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SubSys", "shutdown")
	etLogger_logInfoF("%s_shutdown", SSTrafficInst.name);
	SSTrafficInst.shutdownRequest = 1;
	ET_MSC_LOGGER_SYNC_EXIT
}


void SSTraffic_constructActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SSTraffic", "constructActorInstances")
	ATcpClient_ctor(&_LSTraffic_main_application_light1_trafficLightSocket);
	ATcpClient_ctor(&_LSTraffic_main_application_light2_trafficLightSocket);
	TrafficController_ctor(&_LSTraffic_main_application_controller);
	ET_MSC_LOGGER_SYNC_EXIT
}

void SSTraffic_initActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("SSTraffic", "initActorInstances")
	TrafficlightExampleApplication_init(&_LSTraffic_main_application);
	TrafficLight_init(&_LSTraffic_main_application_light1);
	ATcpClient_init(&_LSTraffic_main_application_light1_trafficLightSocket);
	TrafficLight_init(&_LSTraffic_main_application_light2);
	ATcpClient_init(&_LSTraffic_main_application_light2_trafficLightSocket);
	TrafficController_init(&_LSTraffic_main_application_controller);
	ATimingService_init(&_LSTraffic_main_TimingService);
	ET_MSC_LOGGER_SYNC_EXIT
}

