/**
 * @author generated by eTrice
 *
 * Instance File of SubSystemClass SSTraffic
 * - instantiation of all actor instances and port instances
 * - configuration of data and connection of ports
 */

#include "messaging/etMessageService.h"
#include "platform/etMemory.h"

/* instantiation of message services */

/* MessageService for Thread1 */
static uint8 msgBuffer_Thread1[MESSAGE_POOL_MAX*MESSAGE_BLOCK_SIZE];
static etMessageService msgService_Thread1;


/* include all used ActorClasses */
#include "trafficlight/example/TrafficController.h"
#include "room/basic/service/tcp/ATcpClient.h"
#include "trafficlight/example/TrafficLight.h"
#include "room/basic/service/timing/ATimingService.h"
#include "trafficlight/example/TrafficlightExampleApplication.h"

/* include all used ProtcolClasses */


/* declarations of all ActorClass instances (const and variable structs) */

/* forward declaration of variable actor structs */
static TrafficlightExampleApplication _LSTraffic_main_application;
static TrafficLight _LSTraffic_main_application_light1;
static ATcpClient _LSTraffic_main_application_light1_trafficLightSocket;
static TrafficLight _LSTraffic_main_application_light2;
static ATcpClient _LSTraffic_main_application_light2_trafficLightSocket;
static TrafficController _LSTraffic_main_application_controller;
static ATimingService _LSTraffic_main_TimingService;

/* initialization of variable port structs */		
/* no end ports/SAPs in _LSTraffic_main_application */
/* attributes of _LSTraffic_main_application_light1_timeout */
static PTimerConjPort_var _LSTraffic_main_application_light1_timeout_var={
	0		/* status */
};
/* attributes of _LSTraffic_main_application_light1_blinkerTimeout */
static PTimerConjPort_var _LSTraffic_main_application_light1_blinkerTimeout_var={
	0		/* status */
};
/* attributes of _LSTraffic_main_application_light2_timeout */
static PTimerConjPort_var _LSTraffic_main_application_light2_timeout_var={
	0		/* status */
};
/* attributes of _LSTraffic_main_application_light2_blinkerTimeout */
static PTimerConjPort_var _LSTraffic_main_application_light2_blinkerTimeout_var={
	0		/* status */
};
/* attributes of _LSTraffic_main_application_controller_timeout */
static PTimerConjPort_var _LSTraffic_main_application_controller_timeout_var={
	0		/* status */
};


/* instance _LSTraffic_main_application */
/* no ports/saps/services - nothing to initialize statically */

/* instance _LSTraffic_main_application_light1 */
static const TrafficLight_const _LSTraffic_main_application_light1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{0,&msgService_Thread1, 121, 1} /* Port controller */
	,{0,&msgService_Thread1, 109, 2} /* Port tcpCtrl */
	,{0,&msgService_Thread1, 110, 3} /* Port tcpPayload */
	
	/* data receive ports */
	
	/* saps */
	,{&_LSTraffic_main_application_light1_timeout_var,&msgService_Thread1, 125, 4} /* Port timeout */
	,{&_LSTraffic_main_application_light1_blinkerTimeout_var,&msgService_Thread1, 126, 5} /* Port blinkerTimeout */
	
	/* replicated ports */
	
	/* services */
};
static TrafficLight _LSTraffic_main_application_light1 = {
	&_LSTraffic_main_application_light1_const,
	
	/* data send ports */
	
	/* attributes */
	{
		"127.0.0.1"		/* IPAddr */,
		4441		/* TcpPort */
	}		/* ipConfig */
	
	/* state and history are initialized in init fuction */
};

/* instance _LSTraffic_main_application_light1_trafficLightSocket */
static const ATcpClient_const _LSTraffic_main_application_light1_trafficLightSocket_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{0,&msgService_Thread1, 104, 1} /* Port ControlPort */
	,{0,&msgService_Thread1, 105, 2} /* Port PayloadPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static ATcpClient _LSTraffic_main_application_light1_trafficLightSocket = {
	&_LSTraffic_main_application_light1_trafficLightSocket_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* lastError */,
	{
		0		/* connectionId */,
		0		/* length */,
		{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }		/* data[128] */
	}		/* payload */,
	NULL		/* client */
	
	/* state and history are initialized in init fuction */
};

/* instance _LSTraffic_main_application_light2 */
static const TrafficLight_const _LSTraffic_main_application_light2_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{0,&msgService_Thread1, 122, 1} /* Port controller */
	,{0,&msgService_Thread1, 118, 2} /* Port tcpCtrl */
	,{0,&msgService_Thread1, 119, 3} /* Port tcpPayload */
	
	/* data receive ports */
	
	/* saps */
	,{&_LSTraffic_main_application_light2_timeout_var,&msgService_Thread1, 127, 4} /* Port timeout */
	,{&_LSTraffic_main_application_light2_blinkerTimeout_var,&msgService_Thread1, 128, 5} /* Port blinkerTimeout */
	
	/* replicated ports */
	
	/* services */
};
static TrafficLight _LSTraffic_main_application_light2 = {
	&_LSTraffic_main_application_light2_const,
	
	/* data send ports */
	
	/* attributes */
	{
		"127.0.0.1"		/* IPAddr */,
		4442		/* TcpPort */
	}		/* ipConfig */
	
	/* state and history are initialized in init fuction */
};

/* instance _LSTraffic_main_application_light2_trafficLightSocket */
static const ATcpClient_const _LSTraffic_main_application_light2_trafficLightSocket_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{0,&msgService_Thread1, 113, 1} /* Port ControlPort */
	,{0,&msgService_Thread1, 114, 2} /* Port PayloadPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static ATcpClient _LSTraffic_main_application_light2_trafficLightSocket = {
	&_LSTraffic_main_application_light2_trafficLightSocket_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* lastError */,
	{
		0		/* connectionId */,
		0		/* length */,
		{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }		/* data[128] */
	}		/* payload */,
	NULL		/* client */
	
	/* state and history are initialized in init fuction */
};

/* instance _LSTraffic_main_application_controller */
static const TrafficController_const _LSTraffic_main_application_controller_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{0,&msgService_Thread1, 103, 1} /* Port light1 */
	,{0,&msgService_Thread1, 112, 2} /* Port light2 */
	
	/* data receive ports */
	
	/* saps */
	,{&_LSTraffic_main_application_controller_timeout_var,&msgService_Thread1, 129, 3} /* Port timeout */
	
	/* replicated ports */
	
	/* services */
};
static TrafficController _LSTraffic_main_application_controller = {
	&_LSTraffic_main_application_controller_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init fuction */
};

/* instance _LSTraffic_main_TimingService */
static const etReplSubPort _LSTraffic_main_TimingService_repl_sub_ports[5] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{0,&msgService_Thread1, 106, 1, 0}, /* Repl Sub Port timer idx +0*/
	{0,&msgService_Thread1, 107, 1, 1}, /* Repl Sub Port timer idx +1*/
	{0,&msgService_Thread1, 115, 1, 2}, /* Repl Sub Port timer idx +2*/
	{0,&msgService_Thread1, 116, 1, 3}, /* Repl Sub Port timer idx +3*/
	{0,&msgService_Thread1, 123, 1, 4} /* Repl Sub Port timer idx +4*/
};
static const ATimingService_const _LSTraffic_main_TimingService_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
	{5, _LSTraffic_main_TimingService_repl_sub_ports+0}
};
static ATimingService _LSTraffic_main_TimingService = {
	&_LSTraffic_main_TimingService_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init fuction */
};

