/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.common;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BaseTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.eclipse.etrice.core.common.ui.internal.BaseActivator.getInstance().getInjector("org.eclipse.etrice.core.common.BaseTest");
	}

}
