/*******************************************************************************
 * Copyright (c) 2013 protos software gmbh (http://www.protos.de).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 * 
 * generated by Xtext
 * 
 *******************************************************************************/
package org.eclipse.etrice.core.common.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaseTestUiModule extends org.eclipse.etrice.core.common.ui.AbstractBaseTestUiModule {
	public BaseTestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
