/**
 * @author generated by eTrice
 *
 * this class contains the main function running component SubSys_PedLights
 * it instantiates SubSys_PedLights and starts and ends the lifecycle
 */

package PedLightsController;

import org.eclipse.etrice.runtime.java.modelbase.SubSystemRunnerBase;

class SubSys_PedLightsRunner extends SubSystemRunnerBase {

	/**
     * main function
     * creates the main component and starts and stops the lifecycle
     */
	public static void main(String[] args) {
		// instantiate the main component
		SubSys_PedLights main_component = new SubSys_PedLights("SubSys_PedLights");
		
		run(main_component, args);
	}
};
