/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PContractMonitorControl
 * 
 */

#ifndef _ETRICE_API_CONTRACTS_MONITORS_PCONTRACTMONITORCONTROL_UTILS_H_
#define _ETRICE_API_CONTRACTS_MONITORS_PCONTRACTMONITORCONTROL_UTILS_H_

#include "etrice/api/contracts/monitors/PContractMonitorControl.h"

/*
 * access macros for operations and attributes
*/


#endif /* _ETRICE_API_CONTRACTS_MONITORS_PCONTRACTMONITORCONTROL_UTILS_H_ */

