/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.etmap.ui;

import com.google.inject.Injector;
import org.eclipse.etrice.core.etmap.ui.internal.EtmapActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ETMapExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EtmapActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EtmapActivator activator = EtmapActivator.getInstance();
		return activator != null ? activator.getInjector(EtmapActivator.ORG_ECLIPSE_ETRICE_CORE_ETMAP_ETMAP) : null;
	}

}
