/**
 * @author generated by eTrice
 *
 * Header File of ActorClass Supervisor
 * 
 */

#ifndef _SUPERVISOR_H_
#define _SUPERVISOR_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "SecurityProtocol.h"


typedef struct Supervisor Supervisor;

/* const part of ActorClass (ROM) */
typedef struct Supervisor_const {
	/* simple ports */
	const SecurityProtocolPort application;
	
	/* data receive ports */

	/* saps */
	
	/* replicated ports */
	
	/* services */
} Supervisor_const;


/* constant for state machine data */
#define SUPERVISOR_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct Supervisor {
	const Supervisor_const* const constData;
	
	/* data send ports */

	/*--------------------- attributes ---------------------*/
	
	
		/* state machine variables */
		etInt16 state;
		etInt16 history[SUPERVISOR_HISTORY_SIZE];
};

void Supervisor_init(Supervisor* self);

void Supervisor_receiveMessage(void* self, void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _SUPERVISOR_H_ */

