/*
 * generated by Xtext
 */
package org.eclipse.etrice.core.fsm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.eclipse.etrice.core.fsm.ui.internal.FSMActivator.getInstance().getInjector("org.eclipse.etrice.core.fsm.FSM");
	}

}
